name: stylish_bottom_bar
description: A collection of stylish bottom navigation bars like animated bottom bar and bubble bottom bar for flutter.
version: 1.0.3
#homepage: https://github.com/MarsadMaqsood/Stylish_bottom_bar
repository: https://github.com/MarsadMaqsood/Stylish_bottom_bar

environment:
  sdk: ">=2.18.2 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  
  flutter_test:
    sdk: flutter